export { getDb, type Db } from "./client";
export {
  addVisitorMessage,
  findLatestConversation,
  findOpenConversation,
  getConversation,
  getConversationSummary,
  hasConversation,
  listConversations,
  listVisitorMessages,
  markConversationRead,
  OPEN_STATES,
  requestHumanForVisitor,
  transitionConversation,
  type ConversationDetailRecord,
  type ConversationRecord,
  type ConversationStateValue,
  type ConversationSummaryRecord,
  type HandoffReasonValue,
  type MessageDraft,
  type MessageMemberRecord,
  type MessageRecord,
  type NewConversation,
  type SystemEventValue,
  type TransitionResult,
  type VisitorWrite,
} from "./conversations";
export {
  getWidgetAllowedDomains,
  getWidgetSettings,
  markSnippetInstalled,
  replaceAgentAvatarKey,
  updateWidgetSettings,
  type WidgetColorValue,
  type WidgetPositionValue,
  type WidgetSettingsRecord,
  type WidgetSettingsUpdate,
} from "./widget-settings";
export {
  createVisitor,
  findVisitor,
  recordVisit,
  type StoredVisitorDetails,
  type VisitDetailsUpdate,
  type VisitorRecord,
} from "./visitors";
export {
  createWorkspaceWithOwner,
  findMembershipByUserId,
  getWorkspace,
  type MemberRecord,
  type Membership,
  type WorkspaceRecord,
} from "./workspaces";
