export { getDb, type Db } from "./client";
export {
  addVisitorMessage,
  applyAgentOutcome,
  closeIdleConversation,
  findLatestConversation,
  findOpenConversation,
  getConversation,
  getConversationSummary,
  getMessagesByIds,
  hasConversation,
  hasVisitorConversation,
  isAgentTurnCurrent,
  listConversationHistory,
  listConversations,
  listIdleConversations,
  listVisitorMessages,
  markConversationRead,
  OPEN_STATES,
  requestHumanForVisitor,
  setMessageClassification,
  transitionConversation,
  type AgentOutcome,
  type ConversationDetailRecord,
  type ConversationRecord,
  type ConversationStateValue,
  type ConversationSummaryRecord,
  type HandoffReasonValue,
  type MessageClassificationValue,
  type MessageDraft,
  type MessageMemberRecord,
  type MessageRecord,
  type NewConversation,
  type SystemEventValue,
  type TransitionResult,
  type VisitorWrite,
} from "./conversations";
export {
  getWidgetAllowedDomains,
  getWidgetSettings,
  markSnippetInstalled,
  replaceAgentAvatarKey,
  updateWidgetSettings,
  type WidgetColorValue,
  type WidgetPositionValue,
  type WidgetSettingsRecord,
  type WidgetSettingsUpdate,
} from "./widget-settings";
export {
  createVisitor,
  findVisitor,
  recordVisit,
  type StoredVisitorDetails,
  type VisitDetailsUpdate,
  type VisitorRecord,
} from "./visitors";
export {
  createWorkspaceWithOwner,
  findMembershipByUserId,
  getWorkspace,
  type MemberRecord,
  type Membership,
  type WorkspaceRecord,
} from "./workspaces";
export {
  claimSourceIngest,
  completeSourceIngest,
  createTextSource,
  deleteAbandonedUpload,
  deleteSource,
  failSourceIngest,
  failStaleSource,
  getSource,
  getSourceIngestState,
  listSources,
  listStaleSources,
  markSourceFailed,
  updateTextSource,
  upsertFileSource,
  type ChunkDraft,
  type IngestClaim,
  type SourceDetailRecord,
  type SourceKindValue,
  type SourceRecord,
  type SourceStatusValue,
  type StaleSource,
  type TextSourceSave,
} from "./sources";
export {
  getSuggestedQuestions,
  hasKnowledge,
  knowledgeFingerprint,
  listAgentTurns,
  listKnowledgeSample,
  listReplySources,
  listSourceChunks,
  recordAgentTurn,
  searchChunks,
  setSuggestedQuestions,
  type AgentTurnInput,
  type AgentTurnMatchRecord,
  type AgentTurnRecord,
  type AgentTurnOutcomeValue,
  type ChunkRecord,
  type KnowledgeSampleChunk,
  type ReplySourceRecord,
  type RetrievedChunk,
} from "./knowledge";
