// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8b101c65cbf915c98859bc7b75349fc6df2e44b4370997cdd0814bb6092d1d7c'>;
export type ExecutionHash =
  ExecutionHashBase<'56769a62ebbab13d06c9f3dd6ce9e9dd0f68d88f726bd76b91439dd8c53f0a2a'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Conversation: {
      readonly closedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly handoffReason:
        'low_confidence' | 'no_relevant_knowledge' | 'visitor_requested' | 'agent_off' | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lastMessageAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly lastVisitorMessageAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly ownerReadAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly state: 'ai' | 'waiting' | 'human' | 'closed';
      readonly visitorId: CodecTypes['pg/uuid@1']['output'];
      readonly workspaceId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Member: {
      readonly avatarKey: CodecTypes['pg/text@1']['output'] | null;
      readonly avatarUrl: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: 'owner';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly workspaceId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Message: {
      readonly author: 'visitor' | 'agent' | 'member' | 'system';
      readonly body: CodecTypes['pg/text@1']['output'];
      readonly classification: 'support_question' | 'small_talk' | 'off_topic' | null;
      readonly conversationId: CodecTypes['pg/uuid@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly declined: CodecTypes['pg/bool@1']['output'];
      readonly event: CodecTypes['pg/jsonb@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly memberId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly workspaceId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Visitor: {
      readonly details: CodecTypes['pg/jsonb@1']['output'];
      readonly firstSeenAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly tokenHash: CodecTypes['pg/text@1']['output'];
      readonly visitCount: CodecTypes['pg/int4@1']['output'];
      readonly workspaceId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Workspace: {
      readonly agentAvatarKey: CodecTypes['pg/text@1']['output'] | null;
      readonly agentEnabled: CodecTypes['pg/bool@1']['output'];
      readonly agentName: CodecTypes['pg/text@1']['output'] | null;
      readonly allowedDomains: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly color: 'blue' | 'indigo' | 'violet' | 'pink' | 'red' | 'orange' | 'green';
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly greeting: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly position: 'bottom-left' | 'bottom-right';
      readonly snippetInstalledAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Conversation: {
      readonly closedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly handoffReason:
        'low_confidence' | 'no_relevant_knowledge' | 'visitor_requested' | 'agent_off' | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lastMessageAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly lastVisitorMessageAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly ownerReadAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly state: 'ai' | 'waiting' | 'human' | 'closed';
      readonly visitorId: CodecTypes['pg/uuid@1']['input'];
      readonly workspaceId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Member: {
      readonly avatarKey: CodecTypes['pg/text@1']['input'] | null;
      readonly avatarUrl: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: 'owner';
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly workspaceId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Message: {
      readonly author: 'visitor' | 'agent' | 'member' | 'system';
      readonly body: CodecTypes['pg/text@1']['input'];
      readonly classification: 'support_question' | 'small_talk' | 'off_topic' | null;
      readonly conversationId: CodecTypes['pg/uuid@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly declined: CodecTypes['pg/bool@1']['input'];
      readonly event: CodecTypes['pg/jsonb@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly memberId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly workspaceId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Visitor: {
      readonly details: CodecTypes['pg/jsonb@1']['input'];
      readonly firstSeenAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly tokenHash: CodecTypes['pg/text@1']['input'];
      readonly visitCount: CodecTypes['pg/int4@1']['input'];
      readonly workspaceId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Workspace: {
      readonly agentAvatarKey: CodecTypes['pg/text@1']['input'] | null;
      readonly agentEnabled: CodecTypes['pg/bool@1']['input'];
      readonly agentName: CodecTypes['pg/text@1']['input'] | null;
      readonly allowedDomains: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly color: 'blue' | 'indigo' | 'violet' | 'pink' | 'red' | 'orange' | 'green';
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly greeting: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly position: 'bottom-left' | 'bottom-right';
      readonly snippetInstalledAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly conversations: {
      readonly closed_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly handoff_reason:
        'low_confidence' | 'no_relevant_knowledge' | 'visitor_requested' | 'agent_off' | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly last_message_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly last_visitor_message_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly owner_read_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly state: 'ai' | 'waiting' | 'human' | 'closed';
      readonly visitor_id: CodecTypes['pg/uuid@1']['output'];
      readonly workspace_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly members: {
      readonly avatar_key: CodecTypes['pg/text@1']['output'] | null;
      readonly avatar_url: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: 'owner';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
      readonly workspace_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly messages: {
      readonly author: 'visitor' | 'agent' | 'member' | 'system';
      readonly body: CodecTypes['pg/text@1']['output'];
      readonly classification: 'support_question' | 'small_talk' | 'off_topic' | null;
      readonly conversation_id: CodecTypes['pg/uuid@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly declined: CodecTypes['pg/bool@1']['output'];
      readonly event: CodecTypes['pg/jsonb@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly member_id: CodecTypes['pg/uuid@1']['output'] | null;
      readonly workspace_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly visitors: {
      readonly details: CodecTypes['pg/jsonb@1']['output'];
      readonly first_seen_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly last_seen_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly token_hash: CodecTypes['pg/text@1']['output'];
      readonly visit_count: CodecTypes['pg/int4@1']['output'];
      readonly workspace_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly workspaces: {
      readonly agent_avatar_key: CodecTypes['pg/text@1']['output'] | null;
      readonly agent_enabled: CodecTypes['pg/bool@1']['output'];
      readonly agent_name: CodecTypes['pg/text@1']['output'] | null;
      readonly allowed_domains: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly color: 'blue' | 'indigo' | 'violet' | 'pink' | 'red' | 'orange' | 'green';
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly greeting: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly position: 'bottom-left' | 'bottom-right';
      readonly snippet_installed_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly conversations: {
      readonly closed_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly handoff_reason:
        'low_confidence' | 'no_relevant_knowledge' | 'visitor_requested' | 'agent_off' | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly last_message_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly last_visitor_message_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly owner_read_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly state: 'ai' | 'waiting' | 'human' | 'closed';
      readonly visitor_id: CodecTypes['pg/uuid@1']['input'];
      readonly workspace_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly members: {
      readonly avatar_key: CodecTypes['pg/text@1']['input'] | null;
      readonly avatar_url: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: 'owner';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
      readonly workspace_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly messages: {
      readonly author: 'visitor' | 'agent' | 'member' | 'system';
      readonly body: CodecTypes['pg/text@1']['input'];
      readonly classification: 'support_question' | 'small_talk' | 'off_topic' | null;
      readonly conversation_id: CodecTypes['pg/uuid@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly declined: CodecTypes['pg/bool@1']['input'];
      readonly event: CodecTypes['pg/jsonb@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly member_id: CodecTypes['pg/uuid@1']['input'] | null;
      readonly workspace_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly visitors: {
      readonly details: CodecTypes['pg/jsonb@1']['input'];
      readonly first_seen_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly last_seen_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly token_hash: CodecTypes['pg/text@1']['input'];
      readonly visit_count: CodecTypes['pg/int4@1']['input'];
      readonly workspace_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly workspaces: {
      readonly agent_avatar_key: CodecTypes['pg/text@1']['input'] | null;
      readonly agent_enabled: CodecTypes['pg/bool@1']['input'];
      readonly agent_name: CodecTypes['pg/text@1']['input'] | null;
      readonly allowed_domains: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly color: 'blue' | 'indigo' | 'violet' | 'pink' | 'red' | 'orange' | 'green';
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly greeting: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly position: 'bottom-left' | 'bottom-right';
      readonly snippet_installed_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Conversation = {
    closedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    handoffReason:
      'low_confidence' | 'no_relevant_knowledge' | 'visitor_requested' | 'agent_off' | null;
    id: CodecTypes['pg/uuid@1']['output'];
    lastMessageAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    lastVisitorMessageAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    ownerReadAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    state: 'ai' | 'waiting' | 'human' | 'closed';
    visitorId: CodecTypes['pg/uuid@1']['output'];
    workspaceId: CodecTypes['pg/uuid@1']['output'];
    messages: public_Message[];
    visitor: public_Visitor;
    workspace: public_Workspace;
    readonly [RelationKeys]?: 'messages' | 'visitor' | 'workspace';
  };
  export type public_Member = {
    avatarKey: CodecTypes['pg/text@1']['output'] | null;
    avatarUrl: CodecTypes['pg/text@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    role: 'owner';
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userId: CodecTypes['pg/uuid@1']['output'];
    workspaceId: CodecTypes['pg/uuid@1']['output'];
    messages: public_Message[];
    workspace: public_Workspace;
    readonly [RelationKeys]?: 'messages' | 'workspace';
  };
  export type public_Message = {
    author: 'visitor' | 'agent' | 'member' | 'system';
    body: CodecTypes['pg/text@1']['output'];
    classification: 'support_question' | 'small_talk' | 'off_topic' | null;
    conversationId: CodecTypes['pg/uuid@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    declined: CodecTypes['pg/bool@1']['output'];
    event: CodecTypes['pg/jsonb@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    memberId: CodecTypes['pg/uuid@1']['output'] | null;
    workspaceId: CodecTypes['pg/uuid@1']['output'];
    conversation: public_Conversation;
    member: public_Member | null;
    workspace: public_Workspace;
    readonly [RelationKeys]?: 'conversation' | 'member' | 'workspace';
  };
  export type public_Visitor = {
    details: CodecTypes['pg/jsonb@1']['output'];
    firstSeenAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/uuid@1']['output'];
    lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    tokenHash: CodecTypes['pg/text@1']['output'];
    visitCount: CodecTypes['pg/int4@1']['output'];
    workspaceId: CodecTypes['pg/uuid@1']['output'];
    conversations: public_Conversation[];
    workspace: public_Workspace;
    readonly [RelationKeys]?: 'conversations' | 'workspace';
  };
  export type public_Workspace = {
    agentAvatarKey: CodecTypes['pg/text@1']['output'] | null;
    agentEnabled: CodecTypes['pg/bool@1']['output'];
    agentName: CodecTypes['pg/text@1']['output'] | null;
    allowedDomains: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    color: 'blue' | 'indigo' | 'violet' | 'pink' | 'red' | 'orange' | 'green';
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    greeting: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    position: 'bottom-left' | 'bottom-right';
    snippetInstalledAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    conversations: public_Conversation[];
    members: public_Member[];
    messages: public_Message[];
    visitors: public_Visitor[];
    readonly [RelationKeys]?: 'conversations' | 'members' | 'messages' | 'visitors';
  };
}

export declare const models: {
  public: {
    Conversation: Models.public_Conversation;
    Member: Models.public_Member;
    Message: Models.public_Message;
    Visitor: Models.public_Visitor;
    Workspace: Models.public_Workspace;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly conversations: {
              columns: {
                readonly closed_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly handoff_reason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly last_message_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly last_visitor_message_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly owner_read_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly state: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly visitor_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly workspace_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'conversations_one_open_per_visitor_a2ec6ddc';
                  readonly prefix: 'conversations_one_open_per_visitor';
                  readonly columns: readonly ['visitor_id'];
                  readonly where: "(state <> 'closed')";
                  readonly unique: true;
                },
                {
                  readonly name: 'conversations_workspace_id_idx_90a9f461';
                  readonly prefix: 'conversations_workspace_id_idx';
                  readonly columns: readonly ['workspace_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'conversations_workspace_id_last_message_at_idx_a80869f0';
                  readonly prefix: 'conversations_workspace_id_last_message_at_idx';
                  readonly columns: readonly ['workspace_id', 'last_message_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'conversations';
                    readonly columns: readonly ['workspace_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workspaces';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'conversations';
                    readonly columns: readonly ['visitor_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'visitors';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly members: {
              columns: {
                readonly avatar_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly avatar_url: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly workspace_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['user_id'] }];
              indexes: readonly [
                {
                  readonly name: 'members_workspace_id_idx_90a9f461';
                  readonly prefix: 'members_workspace_id_idx';
                  readonly columns: readonly ['workspace_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'members';
                    readonly columns: readonly ['workspace_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workspaces';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly messages: {
              columns: {
                readonly author: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly body: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', ''>;
                  };
                };
                readonly classification: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly conversation_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly declined: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly event: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly member_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
                readonly workspace_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'messages_conversation_id_created_at_idx_13048a6f';
                  readonly prefix: 'messages_conversation_id_created_at_idx';
                  readonly columns: readonly ['conversation_id', 'created_at'];
                  readonly unique: false;
                },
                {
                  readonly name: 'messages_conversation_id_idx_0c3639df';
                  readonly prefix: 'messages_conversation_id_idx';
                  readonly columns: readonly ['conversation_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'messages_member_id_idx_10d5a0e2';
                  readonly prefix: 'messages_member_id_idx';
                  readonly columns: readonly ['member_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'messages_workspace_id_idx_90a9f461';
                  readonly prefix: 'messages_workspace_id_idx';
                  readonly columns: readonly ['workspace_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['conversation_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'conversations';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['workspace_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workspaces';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'messages';
                    readonly columns: readonly ['member_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'members';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly visitors: {
              columns: {
                readonly details: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly first_seen_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly last_seen_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly token_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly visit_count: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly workspace_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['token_hash'] }];
              indexes: readonly [
                {
                  readonly name: 'visitors_workspace_id_idx_90a9f461';
                  readonly prefix: 'visitors_workspace_id_idx';
                  readonly columns: readonly ['workspace_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'visitors';
                    readonly columns: readonly ['workspace_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'workspaces';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly workspaces: {
              columns: {
                readonly agent_avatar_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly agent_enabled: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly agent_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly allowed_domains: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', readonly []>;
                  };
                };
                readonly color: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'blue'>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly greeting: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly position: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'bottom-right'>;
                  };
                };
                readonly snippet_installed_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly ConversationState: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ai', 'waiting', 'human', 'closed'];
            };
            readonly HandoffReason: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'low_confidence',
                'no_relevant_knowledge',
                'visitor_requested',
                'agent_off',
              ];
            };
            readonly MemberRole: { readonly kind: 'valueSet'; readonly values: readonly ['owner'] };
            readonly MessageAuthor: {
              readonly kind: 'valueSet';
              readonly values: readonly ['visitor', 'agent', 'member', 'system'];
            };
            readonly MessageClassification: {
              readonly kind: 'valueSet';
              readonly values: readonly ['support_question', 'small_talk', 'off_topic'];
            };
            readonly WidgetColor: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'blue',
                'indigo',
                'violet',
                'pink',
                'red',
                'orange',
                'green',
              ];
            };
            readonly WidgetPosition: {
              readonly kind: 'valueSet';
              readonly values: readonly ['bottom-left', 'bottom-right'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly conversations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Conversation';
    };
    readonly members: { readonly namespace: 'public' & NamespaceId; readonly model: 'Member' };
    readonly messages: { readonly namespace: 'public' & NamespaceId; readonly model: 'Message' };
    readonly visitors: { readonly namespace: 'public' & NamespaceId; readonly model: 'Visitor' };
    readonly workspaces: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Workspace';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Conversation: {
            readonly fields: {
              readonly closedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly handoffReason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly lastMessageAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly lastVisitorMessageAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly ownerReadAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly visitorId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly workspaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Message';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['conversationId'];
                };
              };
              readonly visitor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Visitor';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['visitorId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly workspace: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Workspace';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['workspaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'conversations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly closedAt: { readonly column: 'closed_at' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly handoffReason: { readonly column: 'handoff_reason' };
                readonly id: { readonly column: 'id' };
                readonly lastMessageAt: { readonly column: 'last_message_at' };
                readonly lastVisitorMessageAt: { readonly column: 'last_visitor_message_at' };
                readonly ownerReadAt: { readonly column: 'owner_read_at' };
                readonly state: { readonly column: 'state' };
                readonly visitorId: { readonly column: 'visitor_id' };
                readonly workspaceId: { readonly column: 'workspace_id' };
              };
            };
          };
          readonly Member: {
            readonly fields: {
              readonly avatarKey: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly avatarUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly workspaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Message';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['memberId'];
                };
              };
              readonly workspace: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Workspace';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['workspaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'members';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly avatarKey: { readonly column: 'avatar_key' };
                readonly avatarUrl: { readonly column: 'avatar_url' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly role: { readonly column: 'role' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly userId: { readonly column: 'user_id' };
                readonly workspaceId: { readonly column: 'workspace_id' };
              };
            };
          };
          readonly Message: {
            readonly fields: {
              readonly author: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly body: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly classification: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly conversationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly declined: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly event: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly memberId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly workspaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly conversation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Conversation';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['conversationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly member: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Member';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['memberId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly workspace: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Workspace';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['workspaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'messages';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly author: { readonly column: 'author' };
                readonly body: { readonly column: 'body' };
                readonly classification: { readonly column: 'classification' };
                readonly conversationId: { readonly column: 'conversation_id' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly declined: { readonly column: 'declined' };
                readonly event: { readonly column: 'event' };
                readonly id: { readonly column: 'id' };
                readonly memberId: { readonly column: 'member_id' };
                readonly workspaceId: { readonly column: 'workspace_id' };
              };
            };
          };
          readonly Visitor: {
            readonly fields: {
              readonly details: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly firstSeenAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly lastSeenAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly tokenHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly visitCount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly workspaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly conversations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Conversation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['visitorId'];
                };
              };
              readonly workspace: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Workspace';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['workspaceId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'visitors';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly details: { readonly column: 'details' };
                readonly firstSeenAt: { readonly column: 'first_seen_at' };
                readonly id: { readonly column: 'id' };
                readonly lastSeenAt: { readonly column: 'last_seen_at' };
                readonly tokenHash: { readonly column: 'token_hash' };
                readonly visitCount: { readonly column: 'visit_count' };
                readonly workspaceId: { readonly column: 'workspace_id' };
              };
            };
          };
          readonly Workspace: {
            readonly fields: {
              readonly agentAvatarKey: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly agentEnabled: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly agentName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly allowedDomains: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly color: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly greeting: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly snippetInstalledAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly conversations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Conversation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workspaceId'];
                };
              };
              readonly members: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Member';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workspaceId'];
                };
              };
              readonly messages: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Message';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workspaceId'];
                };
              };
              readonly visitors: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Visitor';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['workspaceId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'workspaces';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly agentAvatarKey: { readonly column: 'agent_avatar_key' };
                readonly agentEnabled: { readonly column: 'agent_enabled' };
                readonly agentName: { readonly column: 'agent_name' };
                readonly allowedDomains: { readonly column: 'allowed_domains' };
                readonly color: { readonly column: 'color' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly greeting: { readonly column: 'greeting' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly position: { readonly column: 'position' };
                readonly snippetInstalledAt: { readonly column: 'snippet_installed_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
        };
        readonly enum: {
          readonly ConversationState: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'Ai'; readonly value: 'ai' },
              { readonly name: 'Waiting'; readonly value: 'waiting' },
              { readonly name: 'Human'; readonly value: 'human' },
              { readonly name: 'Closed'; readonly value: 'closed' },
            ];
          };
          readonly HandoffReason: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'LowConfidence'; readonly value: 'low_confidence' },
              { readonly name: 'NoRelevantKnowledge'; readonly value: 'no_relevant_knowledge' },
              { readonly name: 'VisitorRequested'; readonly value: 'visitor_requested' },
              { readonly name: 'AgentOff'; readonly value: 'agent_off' },
            ];
          };
          readonly MemberRole: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [{ readonly name: 'Owner'; readonly value: 'owner' }];
          };
          readonly MessageAuthor: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'Visitor'; readonly value: 'visitor' },
              { readonly name: 'Agent'; readonly value: 'agent' },
              { readonly name: 'Member'; readonly value: 'member' },
              { readonly name: 'System'; readonly value: 'system' },
            ];
          };
          readonly MessageClassification: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'SupportQuestion'; readonly value: 'support_question' },
              { readonly name: 'SmallTalk'; readonly value: 'small_talk' },
              { readonly name: 'OffTopic'; readonly value: 'off_topic' },
            ];
          };
          readonly WidgetColor: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'Blue'; readonly value: 'blue' },
              { readonly name: 'Indigo'; readonly value: 'indigo' },
              { readonly name: 'Violet'; readonly value: 'violet' },
              { readonly name: 'Pink'; readonly value: 'pink' },
              { readonly name: 'Red'; readonly value: 'red' },
              { readonly name: 'Orange'; readonly value: 'orange' },
              { readonly name: 'Green'; readonly value: 'green' },
            ];
          };
          readonly WidgetPosition: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'BottomLeft'; readonly value: 'bottom-left' },
              { readonly name: 'BottomRight'; readonly value: 'bottom-right' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv7'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'conversations';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv7'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'members';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'members';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv7'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'messages';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv7'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'visitors';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv7'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'workspaces';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
        {
          readonly onCreate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly onUpdate: { readonly id: 'instantNow'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'workspaces';
            readonly field: 'updated_at';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
